<?php

/**
 * ScmFaturaItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ScmFaturaItem extends BaseScmFaturaItem
{
	public function postInsert () {
		$this->ScmMaquina->dt_ultimo_faturamento = $this->ScmFaturaDoc->dt_faturamento;
		$this->ScmMaquina->save();
	}
}