<?php

/**
 * ScmHistoricoStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ScmHistoricoStatus extends BaseScmHistoricoStatus
{
	public function preInsert ($event) {
		$this->dt_sistema = DMG_Date::now();
	}
	public function postInsert ($event) {
		$this->ScmMaquina->dt_ultimo_status = $this->dt_status;
		$this->ScmMaquina->id_status = $this->id_status;
		$this->ScmMaquina->save();
	}
}