<?php

/**
 * ScmMovimentacaoDoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ScmMovimentacaoDoc extends BaseScmMovimentacaoDoc
{
	public function preInsert ($event) {
		$this->id_usuario = Zend_Auth::getInstance()->getIdentity()->id;
		$this->dt_sistema = DMG_Date::now();
	}
}