<?php

/**
 * ScmRegularizacaoItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ScmRegularizacaoItem extends BaseScmRegularizacaoItem
{
	public function postInsert ($event) {
		$this->ScmMaquina->nr_cont_1 = $this->nr_cont_1;
		$this->ScmMaquina->nr_cont_2 = $this->nr_cont_2;
		$this->ScmMaquina->nr_cont_3 = $this->nr_cont_3;
		$this->ScmMaquina->nr_cont_4 = $this->nr_cont_4;
		$this->ScmMaquina->nr_cont_5 = $this->nr_cont_5;
		$this->ScmMaquina->nr_cont_6 = $this->nr_cont_6;
		$this->ScmMaquina->dt_ultima_regularizacao = $this->ScmRegularizacaoDoc->dt_regularizacao;
		$this->ScmMaquina->save();
	}

}