<?php

/**
 * ScmTransformacaoDoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ScmTransformacaoDoc extends BaseScmTransformacaoDoc
{
	public function preInsert ($event) {
		$this->dt_sistema = DMG_Date::now();
	}
}