ScmConfig:
  tableName: scm_config
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_config_id
    name:
      type: string()
      fixed: false
      notnull: false
      primary: false
    descricao:
      type: string()
      fixed: false
      notnull: false
      primary: false
    value:
      type: string()
      fixed: false
      notnull: false
      primary: false
    fl_system:
      type: boolean(1)
      notnull: false
      primary: false
