<html>
<head>
    <title>EXT TESTE</title>
</head>
<body>
<style type="text/css">
.x-form-file-wrap {
    position: relative;
    height: 22px;
}
.x-form-file-wrap .x-form-file {
	position: absolute;
	right: 0;
	-moz-opacity: 0;
	filter:alpha(opacity: 0);
	opacity: 0;
	z-index: 2;
    height: 22px;
}
.x-form-file-wrap .x-form-file-btn {
	position: absolute;
	right: 0;
	z-index: 1;
}
.x-form-file-wrap .x-form-file-text {
    position: absolute;
    left: 0;
    z-index: 3;
    color: #777;
}
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $this->BaseUrl(); ?>/extjs/resources/css/ext-all.css" />
<script type="text/javascript" src="<?php echo $this->BaseUrl(); ?>/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->BaseUrl(); ?>/extjs/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->BaseUrl(); ?>/extjs/ux/FileUploadField.js"></script>
<script type="text/javascript">
	Ext.onReady(function() {
		var form = new Ext.form.FormPanel({
			renderTo:'form_div',
			fileUpload: true,
			method:'POST',
			url:'postagens/upload',
			items:[{
				name: 'UPLOAD_IDENTIFIER',
				id:'UPLOAD_IDENTIFIER',
				value: new Date().getTime()
			},{
				xtype:'fileuploadfield',
				fieldLabel:'Arquivo'
			}],
			buttons:[{
				text: 'Enviar',
				scope:this,
				handler:function(){
					form.getForm().submit({
						
						success:function(form, action){
							if(action.result.success){
								alert('eeee');
							}
						}
					});
				}
			}]
		});
	});
</script>
<div id="form_div" style="width:500px"></div>
</body>
</html>
