<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
	"http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title><?php echo DMG_Config::get(2); ?></title>
		<style type="text/css">
			 #loading-mask{
		        position:absolute;
		        left:0;
		        top:0;
		        width:100%;
		        height:100%;
		        z-index:20000;
		        background-color:white;
		    }
		    #loading{
		        position:absolute;
		        left:40%;
		        top:40%;
		        padding:2px;
		        z-index:20001;
		        height:auto;
		    }
		    #loading a {
		        color:#225588;
		    }
		    #loading .loading-indicator{
		        background:white;
		        color:#444;
		        font:bold 13px tahoma,arial,helvetica;
		        padding:10px;
		        margin:0;
		        height:auto;
				width:240px;
		    }
		    #loading-msg {
		        font: normal 10px arial,tahoma,sans-serif;
		    }
			#footer {
		    	position:absolute;
		    	top:480px;
		    	left:0px;
		    	background-color: #DFE8F6;
		    	width: 100%;
		    	height: 75px;
		    	border-top:1px solid #99BBE8;
		    	border-bottom:1px solid #99BBE8;
		    }
		    #mainMsg{
		    	font-size:18px;
		    	width:700px;
		    	position:absolute;
		    	top:176px;
		    	left:186px;
		    }
		    #mainTitle{
		    	position:absolute;
		    	left:185px;
		    	top:140px;
		    	font-size:30px;
		    	width:700px;
		    }
        </style>
        <script type="text/javascript">
			var baseURL = '<?php echo $this->BaseUrl(); ?>/';
			<?php if($this->account):?>
			var accID = <?php echo $this->account; ?>;
			<?php else: ?>
			var accID = -1;
			<?php endif; ?>
			<?php if($this->token):?>
			var accToken = '<?php echo $this->token; ?>';
			<?php endif; ?>
			<?php if($this->personalCliLogo): ?>
			var personalCliLogo = '<?php echo $this->personalCliLogo ?>';
			<?php endif; ?>
			<?php if($this->footerMsg): ?>
			var notaDeRodape = '<?php echo $this->footerMsg ?>';			
			<?php endif; ?>
			var userNameRemember = '<?php echo $this->enableUsrRemember ?>';  //estas variaveis devem sempre estar setadas no javascript, mesmo que nulas...	
			var userPassRemember = '<?php echo $this->enablePassRemember ?>';
		</script>
	</head>
	<body bgcolor="#FFFFFF">
		<div id="loading-mask" style=""></div>
		<div id="loading">
		    <div class="loading-indicator">
		    	<img src="<?php echo $this->BaseUrl(); ?>/images/ajax-loader.gif" width="48" height="48" style="margin-right:8px;float:left;vertical-align:top;"/>
		    	<div style="height: 8px;"></div>
		    	<?php echo DMG_Config::get(2); ?><br />
		    	<span id="loading-msg"><?php echo DMG_Translate::_('i18n.loading'); ?>...</span>
			</div>
		</div>
		<?php foreach($this->css as $script){ ?>
			<script type="text/javascript">document.getElementById('loading-msg').innerHTML = '<?php echo $script; ?>';</script>
			<link rel="stylesheet" type="text/css" href="<?php echo $this->BaseUrl() . '/' .$script; ?>" />
		<?php } ?>
		<?php foreach($this->js as $script){ ?>
			<script type="text/javascript">document.getElementById('loading-msg').innerHTML = '<?php echo $script; ?>';</script>
			<script type="text/javascript" src="<?php echo $this->BaseUrl() . "/" . $script; ?>"></script>
		<?php } ?>
		<script type="text/javascript">
		<?php echo $this->render('index/i18n.js'); ?>
		</script>
	 	<?php if($this->logado):?>
	 	<script type="text/javascript">
			Ext.onReady(Application.app.init, Application.app);
		</script>
	 	<?php else: ?>
			<!-- Pagina de trabalho -->
			
			<div name="background" id="background" style="position: absolute; z-index: 0; visibility: false; left: 600px; top: 50px; display: block; width: 311px; height: 410px; text-align: center; background-image: url(../images/logo-fundo.jpg); background-repeat:no;">
			</div>
			
			<div name="main" id="main" style="float:left; display:block; clear:both; height:100%; width:800px;">
				
				<div name="personalLogo" id="personalLogo" style="margin:50px 0px 30px 180px; float:left;width:100%;">
					<img src="../<?php echo $this->logoPath ?>" />
				</div>
	
				<div id="mainTitle">
					<span style="color: #15428B;font-weight:bold;">
						<?php echo $this->mainTitle ?>
					</span>
				</div>
	
				<div id="mainMsg">
					<span style="color: #666666;position:absolute;">
						<?php echo $this->welcomeMsg ?>
					</span>			
				</div>

				<script language="javascript">
					var logoPath = "<?php echo $this->logoPath ?>";
					Ext.onReady(Application.app.initLogin, Application.app);
				</script>
			</div>

			<div id="footer"> 
				<div style="font-size:12px; padding-top:30px; margin:0px 0px 20px 185px;float:left;" ><?php echo $this->copyright ?></div>
			</div> 
			<!-- Fim de Pagina de trabalho -->
		<?php endif; ?>
	</body>
</html>
