<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
	"http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title><?php echo DMG_Config::get(2); ?></title>
		<style type="text/css">
			 #loading-mask{
		        position:absolute;
		        left:0;
		        top:0;
		        width:100%;
		        height:100%;
		        z-index:20000;
		        background-color:white;
		    }
		    #loading{
		        position:absolute;
		        left:40%;
		        top:40%;
		        padding:2px;
		        z-index:20001;
		        height:auto;
		    }
		    #loading a {
		        color:#225588;
		    }
		    #loading .loading-indicator{
		        background:white;
		        color:#444;
		        font:bold 13px tahoma,arial,helvetica;
		        padding:10px;
		        margin:0;
		        height:auto;
				width:240px;
		    }
		    #loading-msg {
		        font: normal 10px arial,tahoma,sans-serif;
		    }
        </style>
        <script type="text/javascript">
			var baseURL = '<?php echo $this->BaseUrl(); ?>/';
			<?php if($this->account):?>
			var accID = <?php echo $this->account; ?>;
			<?php else: ?>
			var accID = -1;
			<?php endif; ?>
			<?php if($this->token):?>
			var accToken = '<?php echo $this->token; ?>';
			<?php endif; ?>
		</script>
	</head>
	<body>
		<div id="loading-mask" style=""></div>
		<div id="loading">
		    <div class="loading-indicator">
		    	<img src="<?php echo $this->BaseUrl(); ?>/images/ajax-loader.gif" width="48" height="48" style="margin-right:8px;float:left;vertical-align:top;"/>
		    	<div style="height: 8px;"></div>
		    	<?php echo DMG_Config::get(2); ?><br />
		    	<span id="loading-msg"><?php echo DMG_Translate::_('i18n.loading'); ?>...</span>
			</div>
		</div>
		<?php foreach($this->css as $script){ ?>
			<script type="text/javascript">document.getElementById('loading-msg').innerHTML = '<?php echo $script; ?>';</script>
			<link rel="stylesheet" type="text/css" href="<?php echo $this->BaseUrl() . '/' .$script; ?>" />
		<?php } ?>
		<?php foreach($this->js as $script){ ?>
			<script type="text/javascript">document.getElementById('loading-msg').innerHTML = '<?php echo $script; ?>';</script>
			<script type="text/javascript" src="<?php echo $this->BaseUrl() . "/" . $script; ?>"></script>
		<?php } ?>
		<script type="text/javascript">
		<?php echo $this->render('index/i18n.js'); ?>
		</script>
	 	<?php if($this->logado):?>
	 	<script type="text/javascript">
			Ext.onReady(Application.app.init, Application.app);
		</script>
	 	<?php else: ?>
		<script language="javascript">
			Ext.onReady(Application.app.initLogin, Application.app);
		</script>
		<?php endif; ?>
	</body>
</html>