ScaAccount:
  tableName: sca_account
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_account_id
    nome_account:
      type: string()
      fixed: false
      notnull: true
      primary: false
    email_account:
      type: string()
      fixed: false
      notnull: false
      primary: false
    fl_ativa:
      type: boolean(1)
      notnull: true
      primary: false
  relations:
    ScaAccountConfig:
      local: id
      foreign: sca_account_id
      type: many
    ScaClientes:
      local: id
      foreign: sca_account_id
      type: many
    ScaDepartamentos:
      local: id
      foreign: sca_account_id
      type: many
    ScaMensagens:
      local: id
      foreign: sca_account_id
      type: many
    ScaPostagens:
      local: id
      foreign: sca_account_id
      type: many
    ScmGroup:
      local: id
      foreign: sca_account_id
      type: many
    ScmUser:
      local: id
      foreign: sca_account_id
      type: many
ScaAccountConfig:
  tableName: sca_account_config
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_account_config_id
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    nome_parametro:
      type: string()
      fixed: false
      notnull: true
      primary: false
    desc_parametro:
      type: string()
      fixed: false
      notnull: false
      primary: false
    valor_parametro:
      type: string()
      fixed: false
      notnull: false
      primary: false
  relations:
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
ScaAnexos:
  tableName: sca_anexos
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_anexos_id
    sca_postagens_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    nome_anexo:
      type: string()
      fixed: false
      notnull: false
      primary: false
    caminho_anexo:
      type: string()
      fixed: false
      notnull: false
      primary: false
    tipo_anexo:
      type: string()
      fixed: false
      notnull: false
      primary: false
  relations:
    ScaPostagens:
      local: sca_postagens_id
      foreign: id
      type: one
    ScaLogdownloads:
      local: id
      foreign: sca_anexos_id
      type: many
ScaClientes:
  tableName: sca_clientes
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_clientes_id
    cod_cliente:
      type: string()
      fixed: false
      notnull: false
      primary: false
    nome_cliente:
      type: string()
      fixed: false
      notnull: true
      primary: false
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    id_responsavel:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
    fl_acesso_portal:
      type: boolean(1)
      notnull: false
      primary: false
  relations:
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
    ScaPostagens:
      local: id
      foreign: sca_clientes_id
      type: many
    ScmUser:
      local: id
      foreign: sca_clientes_id
      type: many
ScaDepartamentos:
  tableName: sca_departamentos
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_departamentos_id
    cod_departamento:
      type: string()
      fixed: false
      notnull: false
      primary: false
    nome_departamento:
      type: string()
      fixed: false
      notnull: true
      primary: false
    id_gerente:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
  relations:
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
    ScmUser:
      local: id
      foreign: sca_departamentos_id
      type: many
ScaLogdownloads:
  tableName: sca_logdownloads
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_logdownloads_id
    sca_anexos_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    data_download:
      type: timestamp(25)
      notnull: false
      primary: false
    id_usuario:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
  relations:
    ScaAnexos:
      local: sca_anexos_id
      foreign: id
      type: one
ScaLogleituras:
  tableName: sca_logleituras
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_logleituras_id
    sca_postagens_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    data_leitura:
      type: timestamp(25)
      notnull: false
      primary: false
    id_usuario:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
  relations:
    ScaPostagens:
      local: sca_postagens_id
      foreign: id
      type: one
ScaMensagens:
  tableName: sca_mensagens
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_mensagens_id
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    sca_tipo_mensagem_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    sca_status_mensagem_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    sca_postagens_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    data_mensagem:
      type: timestamp(25)
      notnull: false
      primary: false
    remetente:
      type: string()
      fixed: false
      notnull: false
      primary: false
    destinatarios:
      type: string()
      fixed: false
      notnull: false
      primary: false
    assunto:
      type: string()
      fixed: false
      notnull: false
      primary: false
    corpo:
      type: string(1000)
      fixed: false
      notnull: false
      primary: false
  relations:
    ScaPostagens:
      local: sca_postagens_id
      foreign: id
      type: one
    ScaStatusMensagem:
      local: sca_status_mensagem_id
      foreign: id
      type: one
    ScaTipoMensagem:
      local: sca_tipo_mensagem_id
      foreign: id
      type: one
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
    ScaMensagensLog:
      local: id
      foreign: sca_mensagens_id
      type: many
ScaMensagensLog:
  tableName: sca_mensagens_log
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_mensagens_log_id
    sca_mensagens_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    data_log:
      type: timestamp(25)
      notnull: false
      primary: false
    texto_log:
      type: string()
      fixed: false
      notnull: false
      primary: false
  relations:
    ScaMensagens:
      local: sca_mensagens_id
      foreign: id
      type: one
ScaPostagens:
  tableName: sca_postagens
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_postagens_id
    data_postagem:
      type: timestamp(25)
      notnull: false
      primary: false
    texto_postagem:
      type: string(1000)
      fixed: false
      notnull: false
      primary: false
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    sca_clientes_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    scm_user_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    log_leituras:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
    log_downloads:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
    fl_publicado:
      type: boolean(1)
      notnull: false
      primary: false
  relations:
    ScmUser:
      local: scm_user_id
      foreign: id
      type: one
    ScaClientes:
      local: sca_clientes_id
      foreign: id
      type: one
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
    ScaAnexos:
      local: id
      foreign: sca_postagens_id
      type: many
    ScaLogleituras:
      local: id
      foreign: sca_postagens_id
      type: many
    ScaMensagens:
      local: id
      foreign: sca_postagens_id
      type: many
ScaStatusMensagem:
  tableName: sca_status_mensagem
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_status_mensagem_id
    nome_status:
      type: string()
      fixed: false
      notnull: true
      primary: false
  relations:
    ScaMensagens:
      local: id
      foreign: sca_status_mensagem_id
      type: many
ScaTipoMensagem:
  tableName: sca_tipo_mensagem
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: sca_tipo_mensagem_id
    nome_tipo_mensagem:
      type: string()
      fixed: false
      notnull: true
      primary: false
  relations:
    ScaMensagens:
      local: id
      foreign: sca_tipo_mensagem_id
      type: many
ScmConfig:
  tableName: scm_config
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_config_id
    name:
      type: string()
      fixed: false
      notnull: false
      primary: false
    descricao:
      type: string()
      fixed: false
      notnull: false
      primary: false
    value:
      type: string()
      fixed: false
      notnull: false
      primary: false
    fl_system:
      type: boolean(1)
      notnull: false
      primary: false
ScmGroup:
  tableName: scm_group
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_group_id
    name:
      type: string()
      fixed: false
      notnull: true
      primary: false
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
  relations:
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
    ScmGroupRule:
      local: id
      foreign: group_id
      type: many
    ScmUserGroup:
      local: id
      foreign: group_id
      type: many
ScmGroupRule:
  tableName: scm_group_rule
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_group_rule_id
    group_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    rule_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
  relations:
    ScmRule:
      local: rule_id
      foreign: id
      type: one
    ScmGroup:
      local: group_id
      foreign: id
      type: one
ScmModule:
  tableName: scm_module
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_module_id
    name:
      type: string()
      fixed: false
      notnull: true
      primary: false
  relations:
    ScmRule:
      local: id
      foreign: module_id
      type: many
ScmRule:
  tableName: scm_rule
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_rule_id
    name:
      type: string()
      fixed: false
      notnull: true
      primary: false
    description:
      type: string()
      fixed: false
      notnull: false
      primary: false
    module_id:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
  relations:
    ScmModule:
      local: module_id
      foreign: id
      type: one
    ScmGroupRule:
      local: id
      foreign: rule_id
      type: many
ScmUser:
  tableName: scm_user
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_user_id
    sca_account_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    sca_clientes_id:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
    sca_departamentos_id:
      type: integer(4)
      unsigned: false
      notnull: true
      primary: false
    tipo_usuario:
      type: string()
      fixed: false
      notnull: true
      primary: false
    nome_usuario:
      type: string()
      fixed: false
      notnull: true
      primary: false
    login_usuario:
      type: string()
      fixed: false
      notnull: true
      primary: false
    senha_usuario:
      type: string()
      fixed: false
      notnull: true
      primary: false
    recebe_mensagem:
      type: boolean(1)
      notnull: false
      primary: false
    idioma_usuario:
      type: string()
      fixed: false
      notnull: false
      primary: false
    email:
      type: string()
      fixed: false
      notnull: false
      primary: false
    fl_system:
      type: boolean(1)
      notnull: true
      primary: false
    fl_status:
      type: boolean(1)
      notnull: false
      primary: false
  relations:
    ScaDepartamentos:
      local: sca_departamentos_id
      foreign: id
      type: one
    ScaClientes:
      local: sca_clientes_id
      foreign: id
      type: one
    ScaAccount:
      local: sca_account_id
      foreign: id
      type: one
    ScaPostagens:
      local: id
      foreign: scm_user_id
      type: many
    ScmUserGroup:
      local: id
      foreign: user_id
      type: many
ScmUserGroup:
  tableName: scm_user_group
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      sequence: scm_user_group_id
    user_id:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
    group_id:
      type: integer(4)
      unsigned: false
      notnull: false
      primary: false
  relations:
    ScmGroup:
      local: group_id
      foreign: id
      type: one
    ScmUser:
      local: user_id
      foreign: id
      type: one
