<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>{assunto}</title>
		<style type="text/css">
			body {
				margin:0px;
				background-color:#EFEFEF;
				font-family:Verdana, Geneva, sans-serif;
				font-size:12px;
			}
			#wrapper {
				margin: 10px auto;
				width: 80%;
				border:double 2px #CCC;
				background-color:#FFF;
			}
			#header {
				height: 60px;
				padding:10px;
				background-color:#F2F4FF;
				border-bottom:solid 2px #ccc;
				margin-bottom:20px;
			}
			#content{
				padding: 6px;
			}
			h1 {
				font-size:16px;
				color:#29507A;
				font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;
				text-shadow: #A4A4A4 1px 1px 1px;
			}
			hr{
				margin-bottom:20px;
			}
			label{
				font-weight:bold;
				width:100px;
				display:inline-block;
			}
			li{
				padding:3px;
			}
			li.obs{
				line-height:20px;
			}
			li.obs label{
				height:auto;
				margin-bottom:100px;
				display:block;
				float:left;
			}
			#footer{
				clear:both;
				margin-top: 20px;
				border-top:solid 2px #ccc;
				background-color:#9F9F9F;
				height:20px;
				padding:20px;
				vertical-align:middle;
			}
		</style>
	</head>
	
	<body>
		<div id="wrapper">
			<table width="100%" id="header">
				<tr>
					<td width="50%" align="left"><img style="margin:5px;" src="{logoaccount}" /></td>
					<td width="50%" align="right" valign="bottom" style="font-size:14px;font-weight: bold;">{nome_sistema}</td>
				</tr>
			</table>
			<div id="content">
				<h1>{titulo_postagem}</h1>
				<hr />
				<ul type="square">
					<li><label>{mensagem.template.postadopor}</label>: {nome_usuario}</li>
					<li><label>{mensagem.template.data}</label>: {data_postagem}</li>
					<li><label>{mensagem.template.cliente}</label>: {nome_cliente}</li>
					<li class="obs"><label>{mensagem.template.comentario}</label>: {texto_postagem}</li>
				</ul>		
			</div>
			<table width="100%" id="footer">
				<tr>
					<td width="50%" align="left">{footer}</td>
					<td width="50%" align="right" style="font-size:10px;">{copyright}</td>
				</tr>
			</table>
		</div>
	</body>
</html>
